### ISSUE TITLE
Exporting a dat returns an out of range exception

### ISSUE THREAD

**Issue by iceblade112** [xtridence/TO-Toolbox#2] opened 2015-08-15 19:18 UTC
If I try to export a libconfig I have (it's not encrypted), I get this:

```
An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
Additional information: Index was out of range. Must be non-negative and less than the size of the collection.
```

This error occurs at line 385 of DatLoader.cs (`GetValue(row,col)`'s return).

**Comment by xtridence** [comment] 2015-08-16 01:14
I am unable to reproduce the issue. Please send a copy of the libconfig.dat file you are attempting to edit. If you have made changes to the file using the editor, you may want to also indicate the changes that were made.

**Comment by xtridence** [comment] 2015-08-16 01:53
Possible fix issued in https://github.com/TricksterOnline/TO-Toolbox/commit/883d5a55dfdd852d99db6421566b1b94d6e465e2

Let me know if the issue is remedied.

**Comment by iceblade112** [comment] 2015-08-16 02:01
It's the eTO libconfig, actually. I haven't modified it with the editor, but with a text editor.

"Failed to export. Error: Attempting to access non-existant entry (2997,0)"

**Comment by xtridence** [comment] 2015-08-16 02:04
Please send me a copy of the (modified) libconfig file. 
*It is possible that the modified lib config file may not have the correct rowcount specified in the table when it was loaded.

**Comment by iceblade112** [comment] 2015-08-16 02:13
Actually, the second line is this for convenience:

`<INI TableCount = '10000' TableInfoCount = '2000'>`

I assume that's not good? Does the XML reader this uses actually depend on that?

**Comment by xtridence** [comment] 2015-08-16 02:40
Possible fix issued in https://github.com/TricksterOnline/TO-Toolbox/commit/45875b1239a59b76e8a0c1a05aa5f65dc7d38503

Metadata in the INI file are not essential for a regular XML reader. But if they are used for allocating resources, like in the game client, it may cause issues later if the values are arbitrary. I have added a mechanism to repair the file in such a situation.

**Comment by iceblade112** [comment] 2015-08-16 02:45
Etto.. different error now.

```
An unhandled exception of type 'System.NullReferenceException' occurred in CaballaRE.exe
Additional information: Object reference not set to an instance of an object.
```

Line 242 of DatLoader (the declaration of the uint[] result variable + setting / ProcessBlock(b, key, xteaFunc).

The function calling ProcessBlock is EncryptBlock (line 262 of DatLoader), by the way.

I'll send you the modified file in a bit after I finish uploading something.

**Comment by iceblade112** [comment] 2015-08-17 06:01
Sent. Check your RZ PMs @xtridence

**Comment by iceblade112** [comment] 2015-08-17 22:15
I never noticed it said "out of rage"...

RIP English.

**Comment by xtridence** [comment] 2015-08-17 23:27
Issue has been reproduced. A fix has been made, however deployment might be delayed as I am attempting to remedy another blocking issue (memory usage) during export that was found with the provided sample.

**Comment by iceblade112** [comment] 2015-08-18 05:54
Whoo, high memory usage issues :(

They always come to ruin the day. (watches "System" slowly eat up all of my memory with Task Manager on Windows 10)

**Comment by xtridence** [comment] 2015-08-22 12:55
Issues concerning that particular DAT file has been remedied in latest build.

Encryption fix: https://github.com/TricksterOnline/TO-Toolbox/commit/e1c7f08922f76eb50caa6645392d3adc6304bfd7
Memory usage reduction: https://github.com/TricksterOnline/TO-Toolbox/commit/797ac1119484abb14ececd1f42e6ebe9ad9c69de

Note: Memory usage still remains very high during export, but likely won't result in out-of-memory errors.

**Comment by iceblade112** [comment] 2015-08-22 18:13
Cool! Also, the tool also has a problem with loading a Korean libconfig.

**Comment by PyroSamurai** [comment] 2015-08-22 18:22
open a different issue for that. closing this one.

**Closed as completed by PyroSamurai** 2015-08-22 18:22 UTC
Labels: bug
